---
name: Release latest commit with auto-incremented tag
on:
  workflow_dispatch:
  push:
    paths:
      - 'src/main/**'
      - 'pom.xml'
      - '.github/workflows/**'
    branches:
      - "main"
jobs:
  release-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-tags: 'true'
          fetch-depth: 0
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven
          overwrite-settings: false
      - name: Install dependencies
        run: sudo apt update && sudo apt install bc -y
      - name: Setup git
        run: |
          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/$GITHUB_REPOSITORY
          git config --local user.name github-actions
          git config --local user.email github-actions@github.com
      - name: Set NEW_TAG into environment
        run: |
          latest=$(git tag -l --sort=version:refname \
            | grep -E '^v?[0-9]+\.[0-9]+(\.[0-9]+)?$' \
            | tail -n 1 \
            | sed 's/^v//')
          echo "Latest tag: $latest"
          pomVersion=$(mvn -q -Dexec.executable=echo \
            -Dexec.args='${project.version}' \
            --non-recursive \
            exec:exec)
          echo "POM version: $pomVersion"
          [ -n "$latest" ] || latest=$pomVersion
          latestMajor=$(echo -n "$latest" | cut -d '.' -f 1)
          latestMinor=$(echo -n "$latest" | cut -d '.' -f 2)
          latestPatch=$(echo -n "$latest" | cut -d '.' -f 3)
          pomMajor=$(echo -n "$pomVersion" | cut -d '.' -f 1)
          pomMinor=$(echo -n "$pomVersion" | cut -d '.' -f 2)
          pomPatch=$(echo -n "$pomVersion" | cut -d '.' -f 3)
          if [[ "$pomMajor" > "$latestMajor" ]] || [[ "$pomMinor" > "$latestMinor" ]]; then
            newTag="$pomMajor.$pomMinor.$pomPatch"
          else
            if [ -z "${latestPatch}" ]; then patch=0;
            else patch=$(echo "$latestPatch + 1" | bc);
            fi
            newTag="$latestMajor.$latestMinor.$patch"
          fi
          echo NEW_TAG="$newTag" >> "$GITHUB_ENV"
      - name: "Create tag"
        run: git tag ${{ env.NEW_TAG }}; git tag -f latest
      - name: "Push tag"
        run: git push origin ${{ env.NEW_TAG }}; git push -f origin tag latest
      - name: "Set artifact version"
        run: |
          mvn --batch-mode \
            org.codehaus.mojo:versions-maven-plugin:2.16.2:set \
            -DnewVersion=${{ env.NEW_TAG }}
      - name: "Create Release"
        id: create_release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ env.NEW_TAG }}
          name: Release ${{ env.NEW_TAG }}
          generate_release_notes: true
          draft: false
          prerelease: false
      - name: "Run maven build"
        run: mvn --batch-mode clean deploy
        env:
          GITHUB_TOKEN: ${{ secrets.DEPLOY_TOKEN }}
...
