---
name: Run tests

on:
  pull_request:
    paths-ignore:
      - README.md
    branches:
      - main

jobs:
  dependency-review:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout Repository'
        uses: actions/checkout@v4
      - name: 'Dependency Review'
        uses: actions/dependency-review-action@v4
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven
          overwrite-settings: false
      - name: Setup settings.xml
        uses: s4u/maven-settings-action@v3.0.0
        with:
          override: false
          githubServer: false
          servers: |
            [{
                "id": "github",
                "username": "bobz0r75",
                "password": "${{ env.TOKEN }}"
            }]
      - name: Build with Maven
        run: |
          mvn -B clean verify --file pom.xml
